SELECT 
centroid,
node_id,
site,
type,
direct_population,
distance_to_road,
length_fiber_movistar,
length_fiber_azteca,
length_fiber_regional,
length_fiber_third_party,
population_movistar,
population_azteca,
population_regional,
population_third_party,
path_movistar,
fiber_node_movistar::numeric-(SELECT MAX(node_id) FROM {schema}.{table_nodes_roads}) AS fiber_node_movistar,
path_azteca,
fiber_node_azteca::numeric-(SELECT MAX(node_id) FROM {schema}.{table_nodes_roads}) AS fiber_node_azteca,
path_regional,
fiber_node_regional::numeric-(SELECT MAX(node_id) FROM {schema}.{table_nodes_roads}) AS fiber_node_regional,
path_third_party,
fiber_node_third_party::numeric-(SELECT MAX(node_id) FROM {schema}.{table_nodes_roads}) AS fiber_node_third_party,
geom_microwave,
geom_movistar,
geom_azteca,
geom_regional,
geom_third_party
FROM {schema}.{table_path_finder_fiber} O