---
title: "Upload to production CO"
author: "Internet para Todos"
date: "13 de enero de 2018"
output: html_document
---

```{r libraries}
#Load libraries
library(RPostgreSQL)

```

```{r}
#DB Connection parameters
config_path <- '~/shared/rural_planner_colombia/config_files/.config_co'
source(config_path)
```

```{r}
#Export and separate towers, access and transport

drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, dbname = dbname,
                 host = host, port = port,
                 user = user, password = pwd) 

schema_prod <- "rural_planner"
schema_backup <- "rural_planner_backup"
schema_dev <- "rural_planner_dev"

#List of tables that are going to be transfered to production
tables <- c('clusters',
            'clusters_links',
            'coverage',
            'indirect_coverage_polygons',
            'infrastructure_global',
            'settlements',
            'transport_by_settlement',
            'transport_by_tower_all',
            'transport_clusters',
            'transport_greenfield_clusters'
            )


ans<-NA

#Confirmation 
while (!ans %in% c("YES","NO")){
  ans <- readline(prompt="Upload to production schema? (YES/NO): ")
}


if (ans=="YES"){
  
  for(table in tables){
  query <- paste0("DROP TABLE IF EXISTS ", schema_prod,".",table, " CASCADE")
  dbGetQuery(con,query)
  }
  
  for(table in tables){
  query <- paste0("CREATE TABLE ", schema_prod,".",table, " AS 
                  (SELECT * FROM ", schema_dev, ".", table, " )")
  dbGetQuery(con,query)
  }
  
} else if (ans=="NO") {
  stop()
} 


```
